// Trabalhando com erros
/* 
try {
  console.log(numero);
} catch (e) {
  console.log("NÃ£o existo!")
  console.log(e);
} */


